### ISSUE TITLE
Thanks and an issue

### ISSUE THREAD

**Issue by g40** [alvaroferran/OpenCV_CrossInstaller#1]
@alvaroferran Nice work to have packaged this all up. Thank you.

One thing. I am targetting ARM 64. So my config has `ARCHITECTURE="aarch64-linux-gnu"`. But, out of the box, this build fails at the python stage as it tries to reference headers files in the `arm-linux-gnueabihf` directory. I think this is because the `CMAKE_TOOLCHAIN_FILE` is hardwired here: [https://github.com/alvaroferran/OpenCV_CrossInstaller/blob/master/scripts/crossCompile.sh#L14](url)

Sadly, cmake then refuses to configure itself at all with the 64bit compiler. I suspect I need a newer version of gcc/g++. Can you build a 64bit ARM target? I'm trying a native build on a NanoPi K1 (H5) to see how that works ...

[edit] Closing this. Cannot get it to work. Docker, here we come.

**Comment by alvaroferran** [comment]
Hi, thanks! Sorry to hear about it, I haven't tried to build it for a 64-bit system but there shouldn't be any reason not to work that I can think of.
I imagine you'd need to download the gcc and g++ packages for your architecture (gcc-aarch64-linux-gnu and g++-aarch64-linux-gnu) and set it in the offending line in the script, as well as check that there is a folder in the embedded system with that name containing the python files to be retrieved.
